{
 "title": "Historical Data (9/2024)",
 "time": { "from": "2024-08-31T22:00:28.000Z", "to": "2024-09-30T21:55:06.000Z" },
 "panels": [
  {
   "title": "Polielettrolita",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"dewatering_machine\") \n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"portata_poly\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\", \"sensor\"])"
    }
   ]
  },
  {
   "title": "Velocità Tamburo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"dewatering_machine\") \n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"velocita_tamburo\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\", \"sensor\"])"
    }
   ]
  },
  {
   "title": "Velocità Coclea",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"dewatering_machine\") \n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"velocita_coclea\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\", \"sensor\"])"
    }
   ]
  },
  {
   "title": "Umidità Fango",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"dewatering_machine\") \n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"umidita_fango\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\", \"sensor\"])"
    }
   ]
  },
  {
   "title": "Portata Fanghi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"dewatering_machine\") \n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"portata_fanghi\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\", \"sensor\"])"
    }
   ]
  },
  {
   "title": "Torbidità Fango",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"dewatering_machine\") \n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"torbidita_fango\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\", \"sensor\"])"
    }
   ]
  },
  {
   "title": "Torbidità Chiarificato",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"dewatering_machine\") \n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"torbidita_chiarificato\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_field\", \"_value\", \"sensor\"])"
    }
   ]
  }
 ]
}