{
 "title": "Real-time Data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Portata Fanghi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"dewatering_machine_live\")\n  |> range(start: -1h)  // Get data from the last 1 hour\n  |> filter(fn: (r) => r._measurement == \"dewatering_machine\")\n  |> filter(fn: (r) => r._field == \"portata_fanghi\")\n  |> aggregateWindow(every: 1s, fn: mean)  // Downsample to 1-second intervals\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Torbidità Fango",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"dewatering_machine_live\")\n  |> range(start: -1h)  // Get data from the last 1 hour\n  |> filter(fn: (r) => r._measurement == \"dewatering_machine\")\n  |> filter(fn: (r) => r._field == \"torbidita_fango\")\n  |> aggregateWindow(every: 1s, fn: mean)  // Downsample to 1-second intervals\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Velocità Coclea",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"dewatering_machine_live\")\n  |> range(start: -1h)  // Get data from the last 1 hour\n  |> filter(fn: (r) => r._measurement == \"dewatering_machine\")\n  |> filter(fn: (r) => r._field == \"velocita_coclea\")\n  |> aggregateWindow(every: 1s, fn: mean)  // Downsample to 1-second intervals\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Velocità Tamburo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"dewatering_machine_live\")\n  |> range(start: -1h)  // Get data from the last 1 hour\n  |> filter(fn: (r) => r._measurement == \"dewatering_machine\")\n  |> filter(fn: (r) => r._field == \"velocita_tamburo\")\n  |> aggregateWindow(every: 1s, fn: mean)  // Downsample to 1-second intervals\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Polyelectrolyte Inlet Flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"dewatering_machine_live\")\n  |> range(start: -1h)  // Get data from the last 1 hour\n  |> filter(fn: (r) => r._measurement == \"dewatering_machine\")\n  |> filter(fn: (r) => r._field == \"portata_poly\")\n  |> aggregateWindow(every: 1s, fn: mean)  // Downsample to 1-second intervals\n  |> yield(name: \"mean\")  "
    }
   ]
  }
 ]
}